import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-hoenn-dex',
  imports: [],
  templateUrl: './hoenn-dex.html',
  styleUrl: './hoenn-dex.scss'
})
export class HoennDex {

  hoennDexMap: Map<number, NamePokedexNr> = new Map<number, NamePokedexNr>([
    [1, {hoennDexNr: 1, name: "Geckarbor", pokedexNr: 252}],
    [2, {hoennDexNr: 2, name: "Reptain", pokedexNr: 253}],
    [3, {hoennDexNr: 3, name: "Gewaldro", pokedexNr: 254}],
    [4, {hoennDexNr: 4, name: "Flemmli", pokedexNr: 255}],
    [5, {hoennDexNr: 5, name: "Jungglut", pokedexNr: 256}],
    // [6, {name: "Lohgock", pokedexNr: 257}],
    // [7, {name: "Hydropi", pokedexNr: 258}],
    // [8, {name: "Moorabbel", pokedexNr: 259}],
    // [9, {name: "Sumpex", pokedexNr: 260}],
    // [10, {name: "Fiffyen", pokedexNr: 261}],
    // [11, {name: "Magnayen", pokedexNr: 262}],
    // [12, {name: "Zigzachs", pokedexNr: 263}],
    // [13, {name: "Geradaks", pokedexNr: 264}],
    // [14, {name: "Waumpel", pokedexNr: 265}],
    // [15, {name: "Schaloko", pokedexNr: 266}],
    // [16, {name: "Papinella", pokedexNr: 267}],
    // [17, {name: "Panekon", pokedexNr: 268}],
    // [18, {name: "Pudox", pokedexNr: 269}],
    // [19, {name: "Loturzel", pokedexNr: 270}],
    // [20, {name: "Lombrero", pokedexNr: 271}],
    // [21, {name: "Kappalores", pokedexNr: 272}],
    // [22, {name: "Samurzel", pokedexNr: 273}],
    // [23, {name: "Blanas", pokedexNr: 274}],
    // [24, {name: "Tengulist", pokedexNr: 275}],
    // [25, {name: "Schwalbini", pokedexNr: 276}],
    // [26, {name: "Schwalboss", pokedexNr: 277}],
    // [27, {name: "Wingull", pokedexNr: 278}],
    // [28, {name: "Pelipper", pokedexNr: 279}],
    // [29, {name: "Trasla", pokedexNr: 280}],
    // [30, {name: "Kirlia", pokedexNr: 281}],
    // [31, {name: "Guardevoir", pokedexNr: 282}],
    // [32, {name: "Gehweiher", pokedexNr: 283}],
    // [33, {name: "Maskeregen", pokedexNr: 284}],
    // [34, {name: "Knilz", pokedexNr: 285}],
    // [35, {name: "Kapilz", pokedexNr: 286}],
    // [36, {name: "Bummelz", pokedexNr: 287}],
    // [37, {name: "Muntier", pokedexNr: 288}],
    // [38, {name: "Letarking", pokedexNr: 289}],
    // [39, {name: "Abra", pokedexNr: 63}],
    // [40, {name: "Kadabra", pokedexNr: 64}],
    // [41, {name: "Simsala", pokedexNr: 65}],
    // [42, {name: "Nincada", pokedexNr: 290}],
    // [43, {name: "Ninjask", pokedexNr: 291}],
    // [44, {name: "Ninjatom", pokedexNr: 292}],
    // [45, {name: "Flurmel", pokedexNr: 293}],
    // [46, {name: "Krakeelo", pokedexNr: 294}],
    // [47, {name: "Krawumms", pokedexNr: 295}],
    // [48, {name: "Makuhita", pokedexNr: 296}],
    // [49, {name: "Hariyama", pokedexNr: 297}],
    // [50, {name: "Goldini", pokedexNr: 118}],
    // [51, {name: "Golking", pokedexNr: 119}],
    // [52, {name: "Karpador", pokedexNr: 129}],
    // [53, {name: "Garados", pokedexNr: 130}],
    // [54, {name: "Azurill", pokedexNr: 298}],
    // [55, {name: "Marill", pokedexNr: 183}],
    // [56, {name: "Azumarill", pokedexNr: 184}],
    // [57, {name: "Kleinstein", pokedexNr: 74}],
    // [58, {name: "Georok", pokedexNr: 75}],
    // [59, {name: "Geowaz", pokedexNr: 76}],
    // [60, {name: "Nasgnet", pokedexNr: 299}],
    // [61, {name: "Eneco", pokedexNr: 300}],
    // [62, {name: "Enekoro", pokedexNr: 301}],
    // [63, {name: "Zubat", pokedexNr: 41}],
    // [64, {name: "Golbat", pokedexNr: 42}],
    // [65, {name: "Iksbat", pokedexNr: 169}],
    // [66, {name: "Tentacha", pokedexNr: 72}],
    // [67, {name: "Tentoxa", pokedexNr: 73}],
    // [68, {name: "Zobiris", pokedexNr: 302}],
    // [69, {name: "Flunkifer", pokedexNr: 303}],
    // [70, {name: "Stollunior", pokedexNr: 304}],
    // [71, {name: "Stollrak", pokedexNr: 305}],
    // [72, {name: "Stolloss", pokedexNr: 306}],
    // [73, {name: "Machollo", pokedexNr: 66}],
    // [74, {name: "Maschock", pokedexNr: 67}],
    // [75, {name: "Machomei", pokedexNr: 68}],
    // [76, {name: "Meditie", pokedexNr: 307}],
    // [77, {name: "Meditalis", pokedexNr: 308}],
    // [78, {name: "Frizelbliz", pokedexNr: 309}],
    // [79, {name: "Voltenso", pokedexNr: 310}],
    // [80, {name: "Plusle", pokedexNr: 311}],
    // [81, {name: "Minun", pokedexNr: 312}],
    // [82, {name: "Magnetilo", pokedexNr: 81}],
    // [83, {name: "Magneton", pokedexNr: 82}],
    // [84, {name: "Voltobal", pokedexNr: 100}],
    // [85, {name: "Lektrobal", pokedexNr: 101}],
    // [86, {name: "Volbeat", pokedexNr: 313}],
    // [87, {name: "Illumise", pokedexNr: 314}],
    // [88, {name: "Myrapla", pokedexNr: 43}],
    // [89, {name: "Duflor", pokedexNr: 44}],
    // [90, {name: "Giflor", pokedexNr: 45}],
    // [91, {name: "Blubella", pokedexNr: 182}],
    // [92, {name: "Dodu", pokedexNr: 84}],
    // [93, {name: "Dodri", pokedexNr: 85}],
    // [94, {name: "Roselia", pokedexNr: 315}],
    // [95, {name: "Schluppuck", pokedexNr: 316}],
    // [96, {name: "Schlukwech", pokedexNr: 317}],
    // [97, {name: "Kanivanha", pokedexNr: 318}],
    // [98, {name: "Tohaido", pokedexNr: 319}],
    // [99, {name: "Wailmer", pokedexNr: 320}],
    // [100, {name: "Wailord", pokedexNr: 321}]
  ]);
  hoennDexSignal = signal<Map<number, NamePokedexNr>>(this.hoennDexMap);  

  constructor() {}
  
  routeToPokecard(pokedexNr: number) {
    throw new Error('Method not implemented.');
  }
}

interface NamePokedexNr {
  hoennDexNr: number,
  name: string,
  pokedexNr: number
}
