export enum Typen {
    NORMAL = "normal",
    FEUER = "fire",
    WASSER = "water",
    ELEKTRO = "electric",
    PFLANZE = "grass",
    EIS = "ice",
    KAMPF = "fighting",
    GIFT = "poison",
    BODEN = "ground",
    FLUG = "flying",
    PSYCHO = "psychic",
    KÄFER = "bug",
    GESTEIN = "rock",
    GEIST = "ghost",
    DRACHE = "dragon",
    UNLICHT = "dark",
    STAHL = "steel",
    FEE = "fairy"
}
